### ISSUE TITLE
api not found error for app_user

### ISSUE THREAD

**Issue by angelacode** [zendesk/sunshine-conversations-ruby#11]
```
@user_instance = SmoochApi::AppUserApi.new
@user_instance.get_app_user(@app_id, @user_id)
SmoochApi::ApiError: Not Found
from /usr/local/rvm/gems/ruby-2.2.1/gems/smooch-api-1.5.0/lib/smooch-api/api_client.rb:65:in `call_api'
```

**Comment by angelacode** [comment]
I have a proxy and see no calls made:

```
@user_instance.api_client.config.host
=> "api-smooch-io-iif755n5ifs2.runscope.net"
```

**Comment by angelacode** [comment]
Looks like this is reversed??  AppUserResponse get_app_user(app_id, user_id, )

I got it to work with (user_id; app_id) ??

**Comment by mspensieri** [comment]
Hmm it should not be reversed... In the code we see `app_id` and `user_id` injected into the correct places in the path:

https://github.com/smooch/smooch-ruby/blob/5c318280eaa2ef58b753053e271ce0220f2f7bef/lib/smooch-api/api/app_user_api.rb#L163
https://github.com/smooch/smooch-ruby/blob/5c318280eaa2ef58b753053e271ce0220f2f7bef/lib/smooch-api/api/app_user_api.rb#L174
https://github.com/smooch/smooch-ruby/blob/5c318280eaa2ef58b753053e271ce0220f2f7bef/lib/smooch-api/api/app_user_api.rb#L187

Maybe the 404 is due to something else?
